[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "consensus_framework"
version = "0.1.0"
description = "A framework for robust statistical locus selection"
readme = "README.md"
authors = [
    {name = "Connor M. Frankston", email = "franksto@ohsu.edu"}
]
license = {text = "MIT"}
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
]
dependencies = [
    "numpy>=1.20.0",
    "pandas>=1.2.0",
    "statsmodels>=0.12.0",
    "click>=8.0.0",
]

[project.urls]
"Homepage" = "https://github.com/frankston/consensus-framework"
"Bug Tracker" = "https://github.com/frankston/consensus-framework/issues"

[project.scripts]
consensus-framework = "consensus_framework.bed_consensus_cli:construct_consensus_beds"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"

[tool.black]
line-length = 100
target-version = ["py37", "py38", "py39"]

[tool.isort]
profile = "black"
line_length = 100